// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: devices.sql

package db

import (
	"context"
)

const getDeviceByID = `-- name: GetDeviceByID :one
SELECT
    id, name, public_key, state, last_seen, trusted_at
FROM
    devices
WHERE
    id = ?
`

func (q *Queries) GetDeviceByID(ctx context.Context, id string) (Device, error) {
	row := q.db.QueryRowContext(ctx, getDeviceByID, id)
	var i Device
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.PublicKey,
		&i.State,
		&i.LastSeen,
		&i.TrustedAt,
	)
	return i, err
}

const getDevices = `-- name: GetDevices :many
SELECT
    id, name, public_key, state, last_seen, trusted_at
FROM
    devices
`

func (q *Queries) GetDevices(ctx context.Context) ([]Device, error) {
	rows, err := q.db.QueryContext(ctx, getDevices)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Device
	for rows.Next() {
		var i Device
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.PublicKey,
			&i.State,
			&i.LastSeen,
			&i.TrustedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateDeviceStateAndTrust = `-- name: UpdateDeviceStateAndTrust :exec
UPDATE devices
SET
    state = ?,
    trusted_at = ?
WHERE
    id = ?
`

type UpdateDeviceStateAndTrustParams struct {
	State     string
	TrustedAt int64
	ID        string
}

func (q *Queries) UpdateDeviceStateAndTrust(ctx context.Context, arg UpdateDeviceStateAndTrustParams) error {
	_, err := q.db.ExecContext(ctx, updateDeviceStateAndTrust, arg.State, arg.TrustedAt, arg.ID)
	return err
}

const updateLastSeen = `-- name: UpdateLastSeen :exec
UPDATE devices
SET
    last_seen = ?
WHERE
    id = ?
`

type UpdateLastSeenParams struct {
	LastSeen int64
	ID       string
}

func (q *Queries) UpdateLastSeen(ctx context.Context, arg UpdateLastSeenParams) error {
	_, err := q.db.ExecContext(ctx, updateLastSeen, arg.LastSeen, arg.ID)
	return err
}

const updateState = `-- name: UpdateState :exec
UPDATE devices
SET
    state = ?
WHERE
    id = ?
`

type UpdateStateParams struct {
	State string
	ID    string
}

func (q *Queries) UpdateState(ctx context.Context, arg UpdateStateParams) error {
	_, err := q.db.ExecContext(ctx, updateState, arg.State, arg.ID)
	return err
}

const updateTrustedAt = `-- name: UpdateTrustedAt :exec
UPDATE devices
SET
    trusted_at = ?
WHERE
    id = ?
`

type UpdateTrustedAtParams struct {
	TrustedAt int64
	ID        string
}

func (q *Queries) UpdateTrustedAt(ctx context.Context, arg UpdateTrustedAtParams) error {
	_, err := q.db.ExecContext(ctx, updateTrustedAt, arg.TrustedAt, arg.ID)
	return err
}

const upsertDevice = `-- name: UpsertDevice :exec
INSERT INTO
    devices (
        id,
        name,
        public_key,
        state,
        last_seen,
        trusted_at
    )
VALUES
    (?, ?, ?, ?, ?, ?) ON CONFLICT (id) DO
UPDATE
SET
    name = excluded.name,
    public_key = excluded.public_key,
    state = excluded.state,
    last_seen = excluded.last_seen,
    trusted_at = excluded.trusted_at
`

type UpsertDeviceParams struct {
	ID        string
	Name      string
	PublicKey string
	State     string
	LastSeen  int64
	TrustedAt int64
}

func (q *Queries) UpsertDevice(ctx context.Context, arg UpsertDeviceParams) error {
	_, err := q.db.ExecContext(ctx, upsertDevice,
		arg.ID,
		arg.Name,
		arg.PublicKey,
		arg.State,
		arg.LastSeen,
		arg.TrustedAt,
	)
	return err
}
