// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: device_indentity.sql

package db

import (
	"context"
)

const createIdentity = `-- name: CreateIdentity :exec
INSERT INTO
    device_identity (
        id,
        name,
        device_type,
        os,
        os_version,
        arch,
        hostname,
        public_key,
        private_key,
        created_at
    )
VALUES
    (?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
`

type CreateIdentityParams struct {
	ID         string
	Name       string
	DeviceType string
	Os         string
	OsVersion  string
	Arch       string
	Hostname   string
	PublicKey  string
	PrivateKey string
	CreatedAt  int64
}

func (q *Queries) CreateIdentity(ctx context.Context, arg CreateIdentityParams) error {
	_, err := q.db.ExecContext(ctx, createIdentity,
		arg.ID,
		arg.Name,
		arg.DeviceType,
		arg.Os,
		arg.OsVersion,
		arg.Arch,
		arg.Hostname,
		arg.PublicKey,
		arg.PrivateKey,
		arg.CreatedAt,
	)
	return err
}

const getIdentity = `-- name: GetIdentity :one
SELECT
    id, name, device_type, os, os_version, arch, hostname, public_key, private_key, created_at
FROM
    device_identity
LIMIT
    1
`

func (q *Queries) GetIdentity(ctx context.Context) (DeviceIdentity, error) {
	row := q.db.QueryRowContext(ctx, getIdentity)
	var i DeviceIdentity
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.DeviceType,
		&i.Os,
		&i.OsVersion,
		&i.Arch,
		&i.Hostname,
		&i.PublicKey,
		&i.PrivateKey,
		&i.CreatedAt,
	)
	return i, err
}
