// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

type Device struct {
	ID        string
	Name      string
	PublicKey string
	State     string
	LastSeen  int64
	TrustedAt int64
}

type DeviceIdentity struct {
	ID         string
	Name       string
	DeviceType string
	Os         string
	OsVersion  string
	Arch       string
	Hostname   string
	PublicKey  string
	PrivateKey string
	CreatedAt  int64
}
